# Generated by Django 3.2.6 on 2021-09-01 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_email', models.CharField(max_length=100)),
                ('contact_phone', models.IntegerField()),
                ('contact_position', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('uniform', models.TextField()),
                ('description', models.TextField()),
                ('on_site_contact', models.CharField(max_length=100)),
                ('meeting_location', models.CharField(max_length=200)),
                ('staff_needed', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(default='Company', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='shifts', to='schedulr.company')),
                ('created_by', models.ForeignKey(default='Admin', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='shifts', to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(default='Position', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='shifts', to='schedulr.position')),
                ('staff_claimed', models.ForeignKey(default='Worker', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
