# Generated by Django 3.2.7 on 2021-09-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulr', '0002_auto_20210901_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='address',
        ),
        migrations.AddField(
            model_name='shift',
            name='city',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='shift',
            name='state',
            field=models.CharField(default='NA', max_length=2),
        ),
        migrations.AddField(
            model_name='shift',
            name='street',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='shift',
            name='zip',
            field=models.CharField(default='null', max_length=5),
        ),
    ]
