# Generated by Django 3.2.7 on 2021-10-19 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedulr', '0004_auto_20210906_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shift',
            name='full',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shift',
            name='company',
            field=models.ForeignKey(default='Company', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='shifts', to='schedulr.company'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='staff_claimed',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('shifts', models.ManyToManyField(related_name='claimed_shifts', to='schedulr.Shift')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
